### PR TITLE
Fix source distribution and run make distcheck in Travis

### PR DESCRIPTION
**Pull request by ChristopherHogan**
These are the changes required for `make distcheck` to work. Travis will now run `make distcheck` so we can catch distribution bugs earlier. However, since that would double the build times, we only want Travis to do this once per day, not every commit. After this is green and approved, but before merging, I'll set Travis to only run `make distcheck`  if `[ "${TRAVIS_EVENT_TYPE}" == cron ]`. Then Steven can add a daily cron job in the Travis settings.
@stevengj @oskooi @HomerReid

### CODE REVIEW

**Comment by stevengj** [comment]
Maybe we could do `make distcheck` *instead* of `make check`, since the former runs the latter?

**Comment by ChristopherHogan** [comment]
I thought about that, but the nice thing about running `make check` is that it lets us split the `CORETESTS` over the different builds instead of running them all for both python versions. Is there a way to have the best of both worlds?

**Comment by stevengj** [comment]
Can't we use a `CORETESTS` environment variable?

**Comment by ChristopherHogan** [comment]
How do we tell `make distcheck` that `TESTS` should equal `CORETESTS`, but only when it's running `make check` in `meep/tests`?

**Pull request closed without merging**
